{
  "2": {
    "desc": "binary options",
    "type": "ddls",
    "rndrTyp": "img",
    "ctgry": ["forex"],
    "cntry": ["uk","za","au"],
    "domains": [],
    "feed": "",
    "standalone": false,
    "size": "300x250",
    "source": ["http://fmtrader.ck-cdn.com/tn/serve/?cid=386590"],
    "lnk": ["http://go.fmtrader.com/visit/?bta=35192&nci=5687ns"],
    "prdct": ["coms038"],
    "subidkey": "",
    "subidval": "",
    "id": 2
  },
  "3": {
    "desc": "binary options arabic",
    "type": "ddls",
    "rndrTyp": "img",
    "ctgry": ["forex"],
    "cntry": ["tn","ae","lb","sa"],
    "domains": [],
    "feed": "",
    "size": "300x250",
    "standalone": false,
    "source": ["http://fmtrader.ck-cdn.com/tn/serve/?cid=386710"],
    "lnk": ["http://go.fmtrader.com/visit/?bta=35192&nci=5642"],
    "prdct": ["coms038"],
    "subidkey": "",
    "subidval": "",
    "id": 3
  },
  "4": {
    "desc": "binary options russia",
    "type": "ddls",
    "rndrTyp": "img",
    "ctgry": ["forex"],
    "cntry": ["by","ru","ua"],
    "domains": [],
    "feed": "",
    "size": "300x250",
    "standalone": false,
    "source": ["http://fmtrader.ck-cdn.com/tn/serve/?cid=386726"],
    "lnk": ["http://go.fmtrader.com/visit/?bta=35192&nci=5583"],
    "prdct": ["coms038"],
    "subidkey": "",
    "subidval": "",
    "id": 4
  },
  "5": {
    "desc": "binary options italy",
    "type": "ddls",
    "rndrTyp": "img",
    "ctgry": ["forex"],
    "cntry": ["it"],
    "domains": [],
    "feed": "",
    "size": "300x250",
    "standalone": false,
    "source": ["http://fmtrader.ck-cdn.com/tn/serve/?cid=386732"],
    "lnk": ["http://go.fmtrader.com/visit/?bta=35192&nci=5677"],
    "prdct": ["coms038"],
    "subidkey": "",
    "subidval": "",
    "id": 5
  },
  "6": {
    "desc": "888 sport Spain ",
    "type": "ddls",
    "rndrTyp": "img",
    "ctgry": ["sports","news"],
    "cntry": ["es"],
    "domains": [],
    "feed": "",
    "size": "300x250",
    "standalone": false,
    "source": ["https://mmwebhandler.888.com/I/34482?sr=1130293"],
    "lnk": ["https://mmwebhandler.888.com/C/34482?sr=1130293&"],
    "prdct": ["coms038"],
    "subidkey": "",
    "subidval": "",
    "id": 6
  },
  "7": {
    "desc": "miniplay",
    "rndrTyp": "iframe",
    "ctgry": ["video games"],
    "cntry": ["us"],
    "domains": [],
    "feed": "miniplay",
    "size": "300x250",
    "standalone": true,
    "source": ["http://widgets.moosite.com/hot-games/?widget=Affiliate&p=eyJ1c2VySWQiOjYzLCJ0eXBlIjoiMzAweDI1MCAoQiBkYXJrKSIsIm1rdCI6IlpKQUZNT05USUVSQU1PTlRJRVJBIiwib3B0aW9uYWxQYXJhbXMiOnsibWt0YSI6IiIsImNzc0ZpbGUiOiIiLCJtb3JlVXJsIjoiIiwid2ViSWQiOiIxIiwic3NsIjpmYWxzZX19&s=745764f8c159d7f674d8bdcaa3016da0"],
    "lnk": [],
    "prdct": ["coms038"],
    "subidkey": "",
    "subidval": "",
    "id": "7"
  }
}